global:
  scrape_interval: 15s # time to catch new data
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "omnisched-api"
    static_configs:
      - targets: ["host.docker.internal:3333"] # 3333 Fastify/Express port